name = "beloveful"
type = "webpack" # or "javascript" if no bundling needed
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
site = { 
  bucket = "./",       # points to the root folder of your HTML project
  entry-point = "./"   # can be the same
}
